apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sreader
  labels:
    app.kubernetes.io/name: postgres
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgres