-- No-op marker: the Spring Boot rewrite schema no longer creates Gmail delivery
-- or authenticated-fetch tables. Fresh databases contain only feed_url,
-- content_header, content_full_text, and eft_rules.
