package net.sasasin.sreader.orm;

// Generated Aug 13, 2011 9:20:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "ACCOUNT", schema = "PUBLIC", catalog = "SREADER")
public class Account implements java.io.Serializable {

	private String id;
	private String email;
	private String password;
	private Set<Subscriber> subscribers = new HashSet<Subscriber>(0);

	public Account() {
	}

	public Account(String id, String email, String password) {
		this.id = id;
		this.email = email;
		this.password = password;
	}

	public Account(String id, String email, String password,
			Set<Subscriber> subscribers) {
		this.id = id;
		this.email = email;
		this.password = password;
		this.subscribers = subscribers;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "EMAIL", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Subscriber> getSubscribers() {
		return this.subscribers;
	}

	public void setSubscribers(Set<Subscriber> subscribers) {
		this.subscribers = subscribers;
	}

}
