package net.sasasin.sreader.orm;

// Generated Jul 30, 2011 11:16:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContentHeader generated by hbm2java
 */
@Entity
@Table(name = "CONTENT_HEADER", schema = "PUBLIC", catalog = "SREADER")
public class ContentHeader implements java.io.Serializable {

	private String id;
	private FeedUrl feedUrl;
	private String url;
	private String title;
	private Set<ContentFullText> contentFullTexts = new HashSet<ContentFullText>(
			0);

	public ContentHeader() {
	}

	public ContentHeader(String id, FeedUrl feedUrl, String url) {
		this.id = id;
		this.feedUrl = feedUrl;
		this.url = url;
	}

	public ContentHeader(String id, FeedUrl feedUrl, String url, String title,
			Set<ContentFullText> contentFullTexts) {
		this.id = id;
		this.feedUrl = feedUrl;
		this.url = url;
		this.title = title;
		this.contentFullTexts = contentFullTexts;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FEED_URL_ID", nullable = false)
	public FeedUrl getFeedUrl() {
		return this.feedUrl;
	}

	public void setFeedUrl(FeedUrl feedUrl) {
		this.feedUrl = feedUrl;
	}

	@Column(name = "URL", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "TITLE")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contentHeader")
	public Set<ContentFullText> getContentFullTexts() {
		return this.contentFullTexts;
	}

	public void setContentFullTexts(Set<ContentFullText> contentFullTexts) {
		this.contentFullTexts = contentFullTexts;
	}

}
