package net.sasasin.sreader.orm;

// Generated Aug 13, 2011 9:20:57 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ContentView generated by hbm2java
 */
@Entity
@Table(name = "CONTENT_VIEW", schema = "PUBLIC", catalog = "SREADER")
public class ContentView implements java.io.Serializable {

	private ContentViewId id;

	public ContentView() {
	}

	public ContentView(ContentViewId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "accountId", column = @Column(name = "ACCOUNT_ID")),
			@AttributeOverride(name = "email", column = @Column(name = "EMAIL")),
			@AttributeOverride(name = "password", column = @Column(name = "PASSWORD")),
			@AttributeOverride(name = "contentHeaderId", column = @Column(name = "CONTENT_HEADER_ID")),
			@AttributeOverride(name = "url", column = @Column(name = "URL")),
			@AttributeOverride(name = "title", column = @Column(name = "TITLE")),
			@AttributeOverride(name = "fullText", column = @Column(name = "FULL_TEXT")) })
	public ContentViewId getId() {
		return this.id;
	}

	public void setId(ContentViewId id) {
		this.id = id;
	}

}
