package net.sasasin.sreader.orm;

// Generated Sep 11, 2011 1:46:23 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContentHeader generated by hbm2java
 */
@Entity
@Table(name = "content_header")
public class ContentHeader implements java.io.Serializable {

	private static final long serialVersionUID = -4091789063331099978L;
	private String id;
	private FeedUrl feedUrl;
	private String url;
	private String title;
	private Set<ContentFullText> contentFullTexts = new HashSet<ContentFullText>(
			0);

	public ContentHeader() {
	}

	public ContentHeader(String id, FeedUrl feedUrl, String url) {
		this.id = id;
		this.feedUrl = feedUrl;
		this.url = url;
	}

	public ContentHeader(String id, FeedUrl feedUrl, String url, String title,
			Set<ContentFullText> contentFullTexts) {
		this.id = id;
		this.feedUrl = feedUrl;
		this.url = url;
		this.title = title;
		this.contentFullTexts = contentFullTexts;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feed_url_id", nullable = false)
	public FeedUrl getFeedUrl() {
		return this.feedUrl;
	}

	public void setFeedUrl(FeedUrl feedUrl) {
		this.feedUrl = feedUrl;
	}

	@Column(name = "url", nullable = false, length = 8096)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "title", length = 1024)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contentHeader")
	public Set<ContentFullText> getContentFullTexts() {
		return this.contentFullTexts;
	}

	public void setContentFullTexts(Set<ContentFullText> contentFullTexts) {
		this.contentFullTexts = contentFullTexts;
	}

}
