package net.sasasin.sreader.orm;

// Generated Jul 30, 2011 11:16:11 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContentFullText generated by hbm2java
 */
@Entity
@Table(name = "CONTENT_FULL_TEXT", schema = "PUBLIC", catalog = "SREADER")
public class ContentFullText implements java.io.Serializable {

	private String id;
	private ContentHeader contentHeader;
	private Clob fullText;

	public ContentFullText() {
	}

	public ContentFullText(String id, ContentHeader contentHeader) {
		this.id = id;
		this.contentHeader = contentHeader;
	}

	public ContentFullText(String id, ContentHeader contentHeader, Clob fullText) {
		this.id = id;
		this.contentHeader = contentHeader;
		this.fullText = fullText;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CONTENT_HEADER_ID", nullable = false)
	public ContentHeader getContentHeader() {
		return this.contentHeader;
	}

	public void setContentHeader(ContentHeader contentHeader) {
		this.contentHeader = contentHeader;
	}

	@Column(name = "FULL_TEXT")
	public Clob getFullText() {
		return this.fullText;
	}

	public void setFullText(Clob fullText) {
		this.fullText = fullText;
	}

}
