package net.sasasin.sreader.orm;

// Generated Jul 30, 2011 11:16:11 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContentViewId generated by hbm2java
 */
@Embeddable
public class ContentViewId implements java.io.Serializable {

	private String id;
	private String url;
	private String title;
	private Clob fullText;

	public ContentViewId() {
	}

	public ContentViewId(String id, String url, String title, Clob fullText) {
		this.id = id;
		this.url = url;
		this.title = title;
		this.fullText = fullText;
	}

	@Column(name = "ID")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "URL")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "TITLE")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "FULL_TEXT")
	public Clob getFullText() {
		return this.fullText;
	}

	public void setFullText(Clob fullText) {
		this.fullText = fullText;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContentViewId))
			return false;
		ContentViewId castOther = (ContentViewId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null
						&& castOther.getUrl() != null && this.getUrl().equals(
						castOther.getUrl())))
				&& ((this.getTitle() == castOther.getTitle()) || (this
						.getTitle() != null && castOther.getTitle() != null && this
						.getTitle().equals(castOther.getTitle())))
				&& ((this.getFullText() == castOther.getFullText()) || (this
						.getFullText() != null
						&& castOther.getFullText() != null && this
						.getFullText().equals(castOther.getFullText())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37 * result
				+ (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result
				+ (getFullText() == null ? 0 : this.getFullText().hashCode());
		return result;
	}

}
