package net.sasasin.sreader.orm;

// Generated Aug 13, 2011 9:20:57 AM by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContentViewId generated by hbm2java
 */
@Embeddable
public class ContentViewId implements java.io.Serializable {

	private String accountId;
	private String email;
	private String password;
	private String contentHeaderId;
	private String url;
	private String title;
	private Clob fullText;

	public ContentViewId() {
	}

	public ContentViewId(String accountId, String email, String password,
			String contentHeaderId, String url, String title, Clob fullText) {
		this.accountId = accountId;
		this.email = email;
		this.password = password;
		this.contentHeaderId = contentHeaderId;
		this.url = url;
		this.title = title;
		this.fullText = fullText;
	}

	@Column(name = "ACCOUNT_ID")
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "CONTENT_HEADER_ID")
	public String getContentHeaderId() {
		return this.contentHeaderId;
	}

	public void setContentHeaderId(String contentHeaderId) {
		this.contentHeaderId = contentHeaderId;
	}

	@Column(name = "URL")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "TITLE")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "FULL_TEXT")
	public Clob getFullText() {
		return this.fullText;
	}

	public void setFullText(Clob fullText) {
		this.fullText = fullText;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContentViewId))
			return false;
		ContentViewId castOther = (ContentViewId) other;

		return ((this.getAccountId() == castOther.getAccountId()) || (this
				.getAccountId() != null && castOther.getAccountId() != null && this
				.getAccountId().equals(castOther.getAccountId())))
				&& ((this.getEmail() == castOther.getEmail()) || (this
						.getEmail() != null && castOther.getEmail() != null && this
						.getEmail().equals(castOther.getEmail())))
				&& ((this.getPassword() == castOther.getPassword()) || (this
						.getPassword() != null
						&& castOther.getPassword() != null && this
						.getPassword().equals(castOther.getPassword())))
				&& ((this.getContentHeaderId() == castOther
						.getContentHeaderId()) || (this.getContentHeaderId() != null
						&& castOther.getContentHeaderId() != null && this
						.getContentHeaderId().equals(
								castOther.getContentHeaderId())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null
						&& castOther.getUrl() != null && this.getUrl().equals(
						castOther.getUrl())))
				&& ((this.getTitle() == castOther.getTitle()) || (this
						.getTitle() != null && castOther.getTitle() != null && this
						.getTitle().equals(castOther.getTitle())))
				&& ((this.getFullText() == castOther.getFullText()) || (this
						.getFullText() != null
						&& castOther.getFullText() != null && this
						.getFullText().equals(castOther.getFullText())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAccountId() == null ? 0 : this.getAccountId().hashCode());
		result = 37 * result
				+ (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result
				+ (getPassword() == null ? 0 : this.getPassword().hashCode());
		result = 37
				* result
				+ (getContentHeaderId() == null ? 0 : this.getContentHeaderId()
						.hashCode());
		result = 37 * result
				+ (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37 * result
				+ (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result
				+ (getFullText() == null ? 0 : this.getFullText().hashCode());
		return result;
	}

}
