package net.sasasin.sreader.orm;

// Generated Jul 31, 2011 5:27:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EftRules generated by hbm2java
 */
@Entity
@Table(name = "EFT_RULES", schema = "PUBLIC", catalog = "SREADER")
public class EftRules implements java.io.Serializable {

	private String id;
	private String url;
	private String extractRule;

	public EftRules() {
	}

	public EftRules(String id, String url, String extractRule) {
		this.id = id;
		this.url = url;
		this.extractRule = extractRule;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "URL", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "EXTRACT_RULE", nullable = false)
	public String getExtractRule() {
		return this.extractRule;
	}

	public void setExtractRule(String extractRule) {
		this.extractRule = extractRule;
	}

}
