package net.sasasin.sreader.orm;

// Generated Aug 13, 2011 9:20:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FeedUrl generated by hbm2java
 */
@Entity
@Table(name = "FEED_URL", schema = "PUBLIC", catalog = "SREADER")
public class FeedUrl implements java.io.Serializable {

	private String id;
	private String url;
	private Set<Subscriber> subscribers = new HashSet<Subscriber>(0);
	private Set<ContentHeader> contentHeaders = new HashSet<ContentHeader>(0);

	public FeedUrl() {
	}

	public FeedUrl(String id, String url) {
		this.id = id;
		this.url = url;
	}

	public FeedUrl(String id, String url, Set<Subscriber> subscribers,
			Set<ContentHeader> contentHeaders) {
		this.id = id;
		this.url = url;
		this.subscribers = subscribers;
		this.contentHeaders = contentHeaders;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "URL", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feedUrl")
	public Set<Subscriber> getSubscribers() {
		return this.subscribers;
	}

	public void setSubscribers(Set<Subscriber> subscribers) {
		this.subscribers = subscribers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feedUrl")
	public Set<ContentHeader> getContentHeaders() {
		return this.contentHeaders;
	}

	public void setContentHeaders(Set<ContentHeader> contentHeaders) {
		this.contentHeaders = contentHeaders;
	}

}
