package net.sasasin.sreader.orm;

// Generated Jul 31, 2011 5:27:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FeedUrl generated by hbm2java
 */
@Entity
@Table(name = "FEED_URL", schema = "PUBLIC", catalog = "SREADER")
public class FeedUrl implements java.io.Serializable {

	private String id;
	private String url;
	private String authName;
	private String authPassword;
	private String accountId;
	private Set<ContentHeader> contentHeaders = new HashSet<ContentHeader>(0);

	public FeedUrl() {
	}

	public FeedUrl(String id, String url, String accountId) {
		this.id = id;
		this.url = url;
		this.accountId = accountId;
	}

	public FeedUrl(String id, String url, String authName, String authPassword,
			String accountId, Set<ContentHeader> contentHeaders) {
		this.id = id;
		this.url = url;
		this.authName = authName;
		this.authPassword = authPassword;
		this.accountId = accountId;
		this.contentHeaders = contentHeaders;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "URL", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "AUTH_NAME")
	public String getAuthName() {
		return this.authName;
	}

	public void setAuthName(String authName) {
		this.authName = authName;
	}

	@Column(name = "AUTH_PASSWORD")
	public String getAuthPassword() {
		return this.authPassword;
	}

	public void setAuthPassword(String authPassword) {
		this.authPassword = authPassword;
	}

	@Column(name = "ACCOUNT_ID", nullable = false)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feedUrl")
	public Set<ContentHeader> getContentHeaders() {
		return this.contentHeaders;
	}

	public void setContentHeaders(Set<ContentHeader> contentHeaders) {
		this.contentHeaders = contentHeaders;
	}

}
