package net.sasasin.sreader.orm;

// Generated Jul 30, 2011 11:16:11 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GmailLoginInfo generated by hbm2java
 */
@Entity
@Table(name = "GMAIL_LOGIN_INFO", schema = "PUBLIC", catalog = "SREADER")
public class GmailLoginInfo implements java.io.Serializable {

	private String address;
	private String password;
	private String accountId;

	public GmailLoginInfo() {
	}

	public GmailLoginInfo(String address, String accountId) {
		this.address = address;
		this.accountId = accountId;
	}

	public GmailLoginInfo(String address, String password, String accountId) {
		this.address = address;
		this.password = password;
		this.accountId = accountId;
	}

	@Id
	@Column(name = "ADDRESS", unique = true, nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "PASSWORD")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ACCOUNT_ID", nullable = false)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

}
