package net.sasasin.sreader.orm;

// Generated Jul 30, 2011 11:16:11 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LoginRules generated by hbm2java
 */
@Entity
@Table(name = "LOGIN_RULES", schema = "PUBLIC", catalog = "SREADER")
public class LoginRules implements java.io.Serializable {

	private String hostName;
	private String postUrl;
	private String idBoxName;
	private String passwordBoxName;

	public LoginRules() {
	}

	public LoginRules(String hostName, String postUrl, String idBoxName,
			String passwordBoxName) {
		this.hostName = hostName;
		this.postUrl = postUrl;
		this.idBoxName = idBoxName;
		this.passwordBoxName = passwordBoxName;
	}

	@Id
	@Column(name = "HOST_NAME", unique = true, nullable = false)
	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	@Column(name = "POST_URL", nullable = false)
	public String getPostUrl() {
		return this.postUrl;
	}

	public void setPostUrl(String postUrl) {
		this.postUrl = postUrl;
	}

	@Column(name = "ID_BOX_NAME", nullable = false)
	public String getIdBoxName() {
		return this.idBoxName;
	}

	public void setIdBoxName(String idBoxName) {
		this.idBoxName = idBoxName;
	}

	@Column(name = "PASSWORD_BOX_NAME", nullable = false)
	public String getPasswordBoxName() {
		return this.passwordBoxName;
	}

	public void setPasswordBoxName(String passwordBoxName) {
		this.passwordBoxName = passwordBoxName;
	}

}
