package net.sasasin.sreader.orm;

// Generated Sep 11, 2011 1:46:23 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LoginRules generated by hbm2java
 */
@Entity
@Table(name = "login_rules")
public class LoginRules implements java.io.Serializable {

	private static final long serialVersionUID = -8388779913306904792L;
	private String hostName;
	private String postUrl;
	private String idBoxName;
	private String passwordBoxName;

	public LoginRules() {
	}

	public LoginRules(String hostName, String postUrl, String idBoxName,
			String passwordBoxName) {
		this.hostName = hostName;
		this.postUrl = postUrl;
		this.idBoxName = idBoxName;
		this.passwordBoxName = passwordBoxName;
	}

	@Id
	@Column(name = "host_name", unique = true, nullable = false, length = 96)
	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	@Column(name = "post_url", nullable = false, length = 8096)
	public String getPostUrl() {
		return this.postUrl;
	}

	public void setPostUrl(String postUrl) {
		this.postUrl = postUrl;
	}

	@Column(name = "id_box_name", nullable = false, length = 256)
	public String getIdBoxName() {
		return this.idBoxName;
	}

	public void setIdBoxName(String idBoxName) {
		this.idBoxName = idBoxName;
	}

	@Column(name = "password_box_name", nullable = false, length = 256)
	public String getPasswordBoxName() {
		return this.passwordBoxName;
	}

	public void setPasswordBoxName(String passwordBoxName) {
		this.passwordBoxName = passwordBoxName;
	}

}
