package net.sasasin.sreader.orm;

// Generated Sep 11, 2011 1:46:23 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PublishLog generated by hbm2java
 */
@Entity
@Table(name = "publish_log", catalog = "sreader")
public class PublishLog implements java.io.Serializable {

	private String id;
	private String accountId;
	private String contentHeaderId;
	private Date publishDate;

	public PublishLog() {
	}

	public PublishLog(String id, String accountId, String contentHeaderId,
			Date publishDate) {
		this.id = id;
		this.accountId = accountId;
		this.contentHeaderId = contentHeaderId;
		this.publishDate = publishDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "account_id", nullable = false, length = 32)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@Column(name = "content_header_id", nullable = false, length = 32)
	public String getContentHeaderId() {
		return this.contentHeaderId;
	}

	public void setContentHeaderId(String contentHeaderId) {
		this.contentHeaderId = contentHeaderId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "publish_date", nullable = false, length = 10)
	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

}
