package net.sasasin.sreader.orm;

// Generated Jul 30, 2011 11:16:11 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PublishLog generated by hbm2java
 */
@Entity
@Table(name = "PUBLISH_LOG", schema = "PUBLIC", catalog = "SREADER")
public class PublishLog implements java.io.Serializable {

	private String contentHeaderId;

	public PublishLog() {
	}

	public PublishLog(String contentHeaderId) {
		this.contentHeaderId = contentHeaderId;
	}

	@Id
	@Column(name = "CONTENT_HEADER_ID", nullable = false)
	public String getContentHeaderId() {
		return this.contentHeaderId;
	}

	public void setContentHeaderId(String contentHeaderId) {
		this.contentHeaderId = contentHeaderId;
	}

}
