package net.sasasin.sreader.orm;

// Generated Sep 11, 2011 1:46:23 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subscriber generated by hbm2java
 */
@Entity
@Table(name = "subscriber", catalog = "sreader")
public class Subscriber implements java.io.Serializable {

	private String id;
	private FeedUrl feedUrl;
	private Account account;
	private Date subscribeDate;
	private String authName;
	private String authPassword;
	private Date authCheckDate;

	public Subscriber() {
	}

	public Subscriber(String id, FeedUrl feedUrl, Account account) {
		this.id = id;
		this.feedUrl = feedUrl;
		this.account = account;
	}

	public Subscriber(String id, FeedUrl feedUrl, Account account,
			Date subscribeDate, String authName, String authPassword,
			Date authCheckDate) {
		this.id = id;
		this.feedUrl = feedUrl;
		this.account = account;
		this.subscribeDate = subscribeDate;
		this.authName = authName;
		this.authPassword = authPassword;
		this.authCheckDate = authCheckDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feed_url_id", nullable = false)
	public FeedUrl getFeedUrl() {
		return this.feedUrl;
	}

	public void setFeedUrl(FeedUrl feedUrl) {
		this.feedUrl = feedUrl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "subscribe_date", length = 10)
	public Date getSubscribeDate() {
		return this.subscribeDate;
	}

	public void setSubscribeDate(Date subscribeDate) {
		this.subscribeDate = subscribeDate;
	}

	@Column(name = "auth_name", length = 1024)
	public String getAuthName() {
		return this.authName;
	}

	public void setAuthName(String authName) {
		this.authName = authName;
	}

	@Column(name = "auth_password", length = 1024)
	public String getAuthPassword() {
		return this.authPassword;
	}

	public void setAuthPassword(String authPassword) {
		this.authPassword = authPassword;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "auth_check_date", length = 10)
	public Date getAuthCheckDate() {
		return this.authCheckDate;
	}

	public void setAuthCheckDate(Date authCheckDate) {
		this.authCheckDate = authCheckDate;
	}

}
