package net.sasasin.sreader.commons.entity;

// Generated Sep 11, 2011 1:46:23 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ContentView generated by hbm2java
 */
@Entity
@Table(name = "content_view")
public class ContentView implements java.io.Serializable {

	private static final long serialVersionUID = -9041535111840920778L;
	private ContentViewId id;

	public ContentView() {
	}

	public ContentView(ContentViewId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "accountId", column = @Column(name = "account_id", nullable = false, length = 32)),
			@AttributeOverride(name = "email", column = @Column(name = "email", nullable = false, length = 1024)),
			@AttributeOverride(name = "password", column = @Column(name = "password", nullable = false, length = 1024)),
			@AttributeOverride(name = "contentHeaderId", column = @Column(name = "content_header_id", nullable = false, length = 32)),
			@AttributeOverride(name = "url", column = @Column(name = "url", nullable = false, length = 8096)),
			@AttributeOverride(name = "title", column = @Column(name = "title", length = 1024)),
			@AttributeOverride(name = "fullText", column = @Column(name = "full_text")) })
	public ContentViewId getId() {
		return this.id;
	}

	public void setId(ContentViewId id) {
		this.id = id;
	}

}
