package net.sasasin.sreader.commons.entity;

// Generated Sep 11, 2011 1:46:23 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FeedUrl generated by hbm2java
 */
@Entity
@Table(name = "feed_url")
public class FeedUrl implements java.io.Serializable {

	private static final long serialVersionUID = -6036927080531714949L;
	private String id;
	private String url;

	public FeedUrl() {
	}

	public FeedUrl(String id, String url) {
		this.id = id;
		this.url = url;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "url", nullable = false, length = 8096)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
